#!/bin/sh

# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run the brewfile, but always successfully exit for previously installed apps
brew bundle --force || true

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done